services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project-backend
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/projectdb
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: project-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=projectdb

volumes:
  mongo_data:
